# Generated by Django 4.0.3 on 2022-03-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_shopping',
            field=models.BooleanField(default=True),
        ),
    ]
